# Generated by Django 6.0.2 on 2026-04-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapasapp', '0003_alter_account_password_alter_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=300),
        ),
    ]
